version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Contrastive-Counterfactuals-with-GAN/dockerfile
    runtime: nvidia    
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/notebooks
    # command: jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root
